### ISSUE TITLE
关于测试的文件

### ISSUE THREAD

**Issue by suishii** [lc222/char-cnn-text-classification-tensorflow#1]
能请博主上传一下测试的相关代码吗？
另外还有一个问题是：论文中一共有9层，代码里只看到了卷积加上全链接7层？
deep learning 的新手，还请指导！

**Comment by lc222** [comment]
首先关于模型层数的问题，很明显是跟论文中一模一样的，你可以再仔细看一下代码==

然后测试代码的话，可以参考我别的project中的代码，https://github.com/lc222/cnn-text-classification-tf

之所以不会每个项目都写，是因为这种重复造轮子的事情太麻烦，所以如果你有这方面的需求就自己看着写一下就行了
